name: cloud-login
description: ''
inputs:
  vault_addr:
    description: ''
    required: false
  vault_method:
    description: ''
    required: false
  vault_path:
    description: ''
    required: false
  vault_role:
    description: ''
    required: false
  aws_role:
    description: ''
    required: false
  aws_region:
    description: ''
    required: false
  azure_client_id:
    description: ''
    required: false
  azure_tenant_id:
    description: ''
    required: false
  azure_subscription_id:
    description: ''
    required: false
  openstack_config:
    description: ''
    required: false
runs:
  using: composite
  steps:
    # Hashicorp Vault #########################################################
    - uses: hashicorp/vault-action@v2
      if: inputs.vault_addr != ''
      with:
        url: ${{ inputs.vault_addr }}
        method: ${{ inputs.vault_method }}
        path: ${{ inputs.vault_path }}
        role: ${{ inputs.vault_role }}
        exportToken: true

    # AWS #####################################################################
    - uses: aws-actions/configure-aws-credentials@v4
      if: inputs.aws_role != ''
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}

    # Azure ###################################################################
    - uses: azure/login@v1
      if: inputs.azure_client_id != ''
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
    - if: inputs.azure_client_id != ''
      run: |
        echo "ARM_CLIENT_ID=${{ inputs.azure_client_id }}" | tee -a $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ inputs.azure_tenant_id }}" | tee -a $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ inputs.azure_subscription_id }}" | tee -a $GITHUB_ENV
      shell: bash

    # Openstack ###############################################################
    - if: inputs.openstack_config != ''
      run: |
        mkdir -p ${{ github.workspace }}/.config/openstack
        echo "${{ inputs.openstack_config }}" | base64 -d > ${{ github.workspace }}/.config/openstack/cloud.yaml
        echo "OS_CLIENT_CONFIG_FILE=${{ github.workspace }}/.config/openstack/cloud.yaml" | tee -a $GITHUB_ENV
      shell: bash